package view.telas;

import me.control.GerenciadorUsers;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
/**
 *
 * @author ygorc
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        helpUser.setVisible(false);
        helpSenha.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        loginTxt = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JLabel();
        senhaTxt = new javax.swing.JLabel();
        campoUsername = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        botaoEntrar = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        helpUser = new javax.swing.JLabel();
        helpSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));
        desktopPane.setForeground(new java.awt.Color(0, 0, 0));
        desktopPane.setToolTipText("Tela de Login");
        desktopPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desktopPane.setName("Tela de Login"); // NOI18N

        loginTxt.setBackground(new java.awt.Color(255, 255, 255));
        loginTxt.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        loginTxt.setForeground(new java.awt.Color(255, 255, 255));
        loginTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTxt.setText("Login");
        loginTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        desktopPane.add(loginTxt);
        loginTxt.setBounds(0, 50, 400, 30);

        usernameTxt.setForeground(new java.awt.Color(255, 255, 255));
        usernameTxt.setText("Username:");
        desktopPane.add(usernameTxt);
        usernameTxt.setBounds(60, 120, 70, 16);

        senhaTxt.setForeground(new java.awt.Color(255, 255, 255));
        senhaTxt.setText("Senha:");
        desktopPane.add(senhaTxt);
        senhaTxt.setBounds(80, 170, 50, 16);
        desktopPane.add(campoUsername);
        campoUsername.setBounds(130, 120, 170, 22);

        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        desktopPane.add(campoSenha);
        campoSenha.setBounds(130, 170, 170, 22);

        botaoEntrar.setText("Entrar");
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });
        desktopPane.add(botaoEntrar);
        botaoEntrar.setBounds(270, 240, 72, 23);

        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });
        desktopPane.add(botaoLimpar);
        botaoLimpar.setBounds(60, 240, 72, 23);

        helpUser.setForeground(new java.awt.Color(255, 0, 0));
        helpUser.setText("*USUÁRIO INVÁLIDO!");
        desktopPane.add(helpUser);
        helpUser.setBounds(130, 140, 130, 16);

        helpSenha.setForeground(new java.awt.Color(255, 0, 0));
        helpSenha.setText("*SENHA INVÁLIDA!");
        desktopPane.add(helpSenha);
        helpSenha.setBounds(130, 190, 110, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        desktopPane.getAccessibleContext().setAccessibleName("Tela de Login");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // ESSE MÉTODO PODE SER RETIRADO!
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        // TODO: implementar a lógica de verificação de credenciais;
        GerenciadorUsers gerenciador = new GerenciadorUsers();
        String login = campoUsername.getText();
        String senha = String.valueOf(campoSenha.getPassword());
        gerenciador.autenticar(login, senha);
    }//GEN-LAST:event_botaoEntrarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        campoUsername.setText("");
        campoSenha.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUsername;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel helpSenha;
    private javax.swing.JLabel helpUser;
    private javax.swing.JLabel loginTxt;
    private javax.swing.JLabel senhaTxt;
    private javax.swing.JLabel usernameTxt;
    // End of variables declaration//GEN-END:variables

}
