package view.telas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author ygorc
 */
public class TelaAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAdmin
     */
    public TelaAdmin() {
        initComponents();
        
        usernameTxt.setVisible(false);
        senhaTxt.setVisible(false);
        emailTxt.setVisible(false);
        tipoTxt.setVisible(false);
        campoUsername.setVisible(false);
        campoSenha.setVisible(false);
        campoEmail.setVisible(false);
        campoTipo.setVisible(false);
        idTxt.setVisible(false);
        campoId.setVisible(false);
        botaoLimpar.setVisible(false);
        botaoSalvar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastrar = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoDeletarConta = new javax.swing.JButton();
        botaoBuscarUsuario = new javax.swing.JButton();
        botaoListarUsuarios = new javax.swing.JButton();
        botaoBuscarPorID = new javax.swing.JButton();
        usernameTxt = new javax.swing.JLabel();
        emailTxt = new javax.swing.JLabel();
        senhaTxt = new javax.swing.JLabel();
        tipoTxt = new javax.swing.JLabel();
        idTxt = new javax.swing.JLabel();
        campoUsername = new javax.swing.JTextField();
        campoSenha = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        campoTipo = new javax.swing.JTextField();
        campoId = new javax.swing.JTextField();
        botaoLimpar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();

        setTitle("Painel do Administrador");

        botaoCadastrar.setText("Cadastrar Usuário");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoEditar.setText("Editar Usuário");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoDeletarConta.setText("Deletar Conta");
        botaoDeletarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarContaActionPerformed(evt);
            }
        });

        botaoBuscarUsuario.setText("Buscar Usuário");
        botaoBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarUsuarioActionPerformed(evt);
            }
        });

        botaoListarUsuarios.setText("Listar Usuários");
        botaoListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarUsuariosActionPerformed(evt);
            }
        });

        botaoBuscarPorID.setText("Buscar por ID");
        botaoBuscarPorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarPorIDActionPerformed(evt);
            }
        });

        usernameTxt.setText("Username:");

        emailTxt.setText("E-mail:");

        senhaTxt.setText("Senha:");

        tipoTxt.setText("Tipo:");

        idTxt.setText("ID:");

        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoSalvar.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264)
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 163, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(botaoCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoDeletarConta)
                                .addGap(18, 18, 18)
                                .addComponent(botaoBuscarUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(botaoListarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoBuscarPorID))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameTxt)
                                    .addComponent(senhaTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emailTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tipoTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(idTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoUsername)
                                    .addComponent(campoSenha)
                                    .addComponent(campoEmail)
                                    .addComponent(campoTipo)
                                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrar)
                    .addComponent(botaoEditar)
                    .addComponent(botaoDeletarConta)
                    .addComponent(botaoBuscarUsuario)
                    .addComponent(botaoListarUsuarios)
                    .addComponent(botaoBuscarPorID))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTxt)
                    .addComponent(campoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaTxt)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTxt)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoTxt)
                    .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTxt)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoLimpar)
                    .addComponent(botaoSalvar))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscarPorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarPorIDActionPerformed
        // TODO: Lógica da busca por ID
        usernameTxt.setVisible(false);
        senhaTxt.setVisible(false);
        emailTxt.setVisible(false);
        tipoTxt.setVisible(false);
        campoUsername.setVisible(false);
        campoSenha.setVisible(false);
        campoEmail.setVisible(false);
        campoTipo.setVisible(false);
        idTxt.setVisible(true);
        campoId.setVisible(true);
        botaoLimpar.setVisible(false);
        botaoSalvar.setVisible(false); 
    }//GEN-LAST:event_botaoBuscarPorIDActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        campoEmail.setText("");
        campoId.setText("");
        campoSenha.setText("");
        campoTipo.setText("");
        campoUsername.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        usernameTxt.setVisible(true);
        senhaTxt.setVisible(true);
        emailTxt.setVisible(true);
        tipoTxt.setVisible(true);
        campoUsername.setVisible(true);
        campoSenha.setVisible(true);
        campoEmail.setVisible(true);
        campoTipo.setVisible(true);
        idTxt.setVisible(false);
        campoId.setVisible(false);
        botaoLimpar.setVisible(true);
        botaoSalvar.setVisible(true);
        
        //TODO: Fazer a lógiga do cadastro;
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        usernameTxt.setVisible(true);
        senhaTxt.setVisible(true);
        emailTxt.setVisible(true);
        tipoTxt.setVisible(true);
        campoUsername.setVisible(true);
        campoSenha.setVisible(true);
        campoEmail.setVisible(true);
        campoTipo.setVisible(true);
        idTxt.setVisible(true);
        campoId.setVisible(true);
        botaoLimpar.setVisible(true);
        botaoSalvar.setVisible(true);
        
        //TODO: Fazer a lógica da edição;
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoDeletarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarContaActionPerformed
        usernameTxt.setVisible(false);
        senhaTxt.setVisible(false);
        emailTxt.setVisible(false);
        tipoTxt.setVisible(false);
        campoUsername.setVisible(false);
        campoSenha.setVisible(false);
        campoEmail.setVisible(false);
        campoTipo.setVisible(false);
        idTxt.setVisible(true);
        campoId.setVisible(true);
        botaoLimpar.setVisible(false);
        botaoSalvar.setVisible(false);
        
        // TODO: Fazer a lógica de delete
    }//GEN-LAST:event_botaoDeletarContaActionPerformed

    private void botaoBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarUsuarioActionPerformed
        usernameTxt.setVisible(true);
        senhaTxt.setVisible(false);
        emailTxt.setVisible(true);
        tipoTxt.setVisible(false);
        campoUsername.setVisible(false);
        campoSenha.setVisible(false);
        campoEmail.setVisible(false);
        campoTipo.setVisible(false);
        idTxt.setVisible(false);
        campoId.setVisible(false);
        botaoLimpar.setVisible(false);
        botaoSalvar.setVisible(false);
        
        //TODO: Fazer a lógica para a busca através do Username ou E-mail
    }//GEN-LAST:event_botaoBuscarUsuarioActionPerformed

    private void botaoListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarUsuariosActionPerformed
        
        
        ListaUsuarios listaUsuarios = new ListaUsuarios();
        listaUsuarios.setVisible(true);
    }//GEN-LAST:event_botaoListarUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscarPorID;
    private javax.swing.JButton botaoBuscarUsuario;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoDeletarConta;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoListarUsuarios;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JTextField campoUsername;
    private javax.swing.JLabel emailTxt;
    private javax.swing.JLabel idTxt;
    private javax.swing.JLabel senhaTxt;
    private javax.swing.JLabel tipoTxt;
    private javax.swing.JLabel usernameTxt;
    // End of variables declaration//GEN-END:variables
}
