package view.telas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author ygorc
 */
public class TelaUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaUser
     */
    public TelaUser() {
        initComponents();
        botaoConfirmar.setVisible(false);
        botaoLimpar.setVisible(false);
        txtFormaPagamento.setVisible(false);
        txtIdFilme.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoListaFilmes = new javax.swing.JButton();
        botaoAlugaFilme = new javax.swing.JButton();
        txtIdFilme = new javax.swing.JLabel();
        campoIdFilme = new javax.swing.JTextField();
        botaoConfirmar = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        txtFormaPagamento = new javax.swing.JLabel();
        campoFormaPagamento = new javax.swing.JTextField();

        setTitle("Painel do Usuário");
        setToolTipText("");

        botaoListaFilmes.setText("Catálogo de Filmes");
        botaoListaFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaFilmesActionPerformed(evt);
            }
        });

        botaoAlugaFilme.setText("Alugar Filme");
        botaoAlugaFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlugaFilmeActionPerformed(evt);
            }
        });

        txtIdFilme.setText("ID do filme:");

        botaoConfirmar.setText("Confirmar");
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });

        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        txtFormaPagamento.setText("Forma de Pagamento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFormaPagamento)
                            .addComponent(txtIdFilme))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoIdFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(botaoListaFilmes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(botaoLimpar)
                        .addGap(68, 68, 68)
                        .addComponent(botaoConfirmar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(botaoAlugaFilme)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(botaoListaFilmes)
                .addGap(18, 18, 18)
                .addComponent(botaoAlugaFilme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdFilme)
                    .addComponent(campoIdFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFormaPagamento)
                    .addComponent(campoFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConfirmar)
                    .addComponent(botaoLimpar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoListaFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaFilmesActionPerformed
        TelaCatalogo catalogo = new TelaCatalogo();
        catalogo.setVisible(true);
    }//GEN-LAST:event_botaoListaFilmesActionPerformed

    private void botaoAlugaFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlugaFilmeActionPerformed
        botaoConfirmar.setVisible(true);
        botaoLimpar.setVisible(true);
        txtFormaPagamento.setVisible(true);
        txtIdFilme.setVisible(true);
    }//GEN-LAST:event_botaoAlugaFilmeActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        botaoConfirmar.setText("");
        botaoLimpar.setText("");
        txtFormaPagamento.setText("");
        txtIdFilme.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        // TODO: Lógica de confirmação, verifica se o ID do filme existe.
    }//GEN-LAST:event_botaoConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlugaFilme;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoListaFilmes;
    private javax.swing.JTextField campoFormaPagamento;
    private javax.swing.JTextField campoIdFilme;
    private javax.swing.JLabel txtFormaPagamento;
    private javax.swing.JLabel txtIdFilme;
    // End of variables declaration//GEN-END:variables
}
